### ISSUE TITLE
Column names with spaces can't be handled

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/gitsheets#12]
The path template validation pattern fails if your template is e.g. `{{Student Number}}` -- I don't know if that's even valid handlebars though

**Comment by timwis** [comment]
Handlebars doesn't support spaces in field names; it would assume you're trying to pass `Number` to a helper function called `Student`. I assume we don't want to convert all field names to underscore-separated, so I've swapped handlebars for a super simple template lib by my old pal yoshuawuts called [maxstache](https://github.com/yoshuawuyts/maxstache) :D

**Comment by themightychris** [comment]
That's perfect for now
