### ISSUE TITLE
Consider sanitising commit message input on merge

### ISSUE THREAD

**Issue by timwis** [JarvusInnovations/gitsheets#27]
The merge API call allows an optional `msg` query parameter to provide a message for the merge commit. When testing, it seems special characters, quotes, etc. work fine and don't break anything. But I may just need more coffee and be forgetting something crucial. It's very easy to add in validation/sanitising; we just need the right regex string for it.

EDIT: Apart from string length of course

**Comment by themightychris** [comment]
As written in #28, the `msg` param should handle arbitrary clobs just fine I believe, it could even be a multi-line document with multiple embedded formats. `git-client` just needs to handle the shell escaping properly, which it should already
