### ISSUE TITLE
explode test hangs

### ISSUE THREAD

**Issue by timwis** [JarvusInnovations/gitsheets#3]
The test completes successfully, but the process hangs. At first I thought there was an issue with my readable string fixture, but I think it may have to do with the git-client library's spawning of git. Needs further investigation.

**Comment by themightychris** [comment]
There's a cleanup method you can call, some hologit commands do it. When
you start building trees it keeps a pipe open to a batch git-mktree
session. There's an eventual timeout. Probably going to bring tree hashing
into node-native code soon

**Comment by timwis** [comment]
This stopped hanging a while ago, assuming because of some fix in hologit or because magic.

**Comment by themightychris** [comment]
great, probably the parallel tree writing bug we fixed for gitsheets
