### ISSUE TITLE
Usage example / getting started

### ISSUE THREAD

**Issue by brockfanning** [JarvusInnovations/gitsheets#35]
Hi all, this seems like a project that I would be interested in. Can anyone provide an example of how this would be used, and/or a few steps on getting started? I've tried running locally, and also starting with Chef Habitat, but nothing jumped out at me for next steps. Thank you for any tips!

**Comment by themightychris** [comment]
Hi @brockfanning ! We're still pretty early in development, but are excited to have caught your attention already

Currently the project is more amalgamation of Proofs-of-Concept features, and we're planning out now how we're going to tie up an initial MVP experience. Stay tuned!

**Comment by brockfanning** [comment]
I was just checking in and saw this file - https://github.com/JarvusInnovations/gitsheets/blob/master/docs/quick-demo.md - which is exactly what I was thinking of here. So I'll go ahead and close this. Thanks for adding that!

**Comment by themightychris** [comment]
@brockfanning check out the whole docs site that's coming together: https://docs.gitsheets.com/quick-demo/
